language: python
python:
  - "3.6"

stages:
  - test
  - lint
  - name: deploy
    if: branch = master

install:
  - pip install --index-url https://test.pypi.org/simple/ -r requirements-test.txt --extra-index-url https://pypi.org/simple/ -r requirements.txt
  - pip install flake8

before_deploy:
  - pip install --user --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: pytest
    - stage: lint
      name: "flake8"
      script: flake8 --ignore=F401 cloud_scanner_azure
    - stage: deploy
      name: "Sphinx Documentation"
      script: sh deploy.sh
      name: "PyPi Packages"
      script: skip
      provider: pypi
      user:
        secure: ""
      password:
        secure: ""
      server: https://test.pypi.org/legacy/
      on:
        tags: true
